# verify.py

from fastapi import FastAPI, Query
from fastapi.responses import JSONResponse
from pydantic import BaseModel
import json
import os
import time

app = FastAPI()

# Constants
WINDOW_DURATION = 2  # seconds per window
CODES_FILE = "results/window_codes.json"  # generated by main.py


class VerifyResponse(BaseModel):
    input_code: str
    valid: bool
    matched_window: int | None


def get_current_window_id() -> int:
    """Return the current time window index based on time and window duration."""
    return int(time.time() // WINDOW_DURATION)


@app.get("/verify", response_model=VerifyResponse)
def verify_code(code: str = Query(...)):
    if not os.path.exists(CODES_FILE):
        return JSONResponse(
            status_code=500,
            content={"error": f"{CODES_FILE} not found"}
        )

    with open(CODES_FILE, "r") as f:
        try:
            codes = json.load(f)
        except json.JSONDecodeError:
            return JSONResponse(
                status_code=500,
                content={"error": "Invalid JSON format in window_codes.json"}
            )

    # Parse the JSON as window_id → hash_code map
    code_dict = {
        entry["window_id"]: entry["hash_code"]
        for entry in codes
        if "window_id" in entry and "hash_code" in entry
    }

    # Get current window ID
    current_window = get_current_window_id()

    # Allow checking against [current, current-1, current+1] window codes
    for window_offset in [-1, 0, 1]:
        check_id = current_window + window_offset
        if check_id in code_dict and code == code_dict[check_id]:
            return VerifyResponse(
                input_code=code,
                valid=True,
                matched_window=check_id
            )

    return VerifyResponse(
        input_code=code,
        valid=False,
        matched_window=None
    )
